version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/SampleApp
hooks:
  BeforeInstall:
    - location: scripts/setup_dirs.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_services.sh
    - location: scripts/pipenv.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
